export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE"
    
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE"
}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
    GET_SINGLE_PRODUCTS_SUCCESS: "GET_SINGLE_PRODUCTS_SUCCESS",
    GET_SINGLE_PRODUCTS_FAILURE: "GET_SINGLE_PRODUCTS_FAILURE",
    GET_SINGLE_PRODUCTS_REQUEST: "GET_SINGLE_PRODUCTS_REQUEST"
}

export const cartConstants = {
    CART_ADD_ITEM : 'CART_ADD_ITEM',
    CART_REMOVE_ITEM : 'CART_REMOVE_ITEM',
    CART_SAVE_SHIPPING : 'CART_SAVE_SHIPPING',
    CART_SAVE_PAYMENT : 'CART_SAVE_PAYMENT'
}